/**
 * Markdown Export Service
 * Generates copy-paste friendly markdown digests of news articles
 */

import { prisma } from '../lib/prisma.js';

interface ExportOptions {
  userId?: string;
  articleIds?: string[];
  dateFrom?: Date;
  dateTo?: Date;
}

export async function generateNewsDigestMarkdown(options: ExportOptions): Promise<string> {
  const { userId, articleIds, dateFrom, dateTo } = options;

  let userName = 'User';

  if (userId) {
    const user = await prisma.user.findUnique({
      where: { id: userId },
    });
    if (!user) {
      throw new Error('User not found');
    }
    userName = user.name || user.email;
  }

  // Fetch articles — by IDs or by user
  let articles;
  if (articleIds && articleIds.length > 0) {
    articles = await prisma.newsArticle.findMany({
      where: { id: { in: articleIds } },
      include: {
        company: true,
        person: true,
        tag: true,
      },
      orderBy: [{ publishedAt: 'desc' }],
    });
  } else if (userId) {
    const defaultDateFrom = new Date();
    defaultDateFrom.setDate(defaultDateFrom.getDate() - 7);

    articles = await prisma.newsArticle.findMany({
      where: {
        articleUsers: { some: { userId } },
        publishedAt: {
          gte: dateFrom || defaultDateFrom,
          lte: dateTo || new Date(),
        },
      },
      include: {
        company: true,
        person: true,
        tag: true,
      },
      orderBy: [{ publishedAt: 'desc' }],
    });
  } else {
    throw new Error('Either userId or articleIds must be provided');
  }

  const formatArticle = (article: typeof articles[0]): string => {
    const lines: string[] = [];

    lines.push(`### ${article.headline}`);
    lines.push('');

    const badges = [
      article.company?.name,
      article.tag?.name,
      article.matchType ? `[${article.matchType.toUpperCase()}]` : null,
    ].filter(Boolean);

    if (badges.length > 0) {
      lines.push(`**${badges.join(' | ')}**`);
      lines.push('');
    }

    if (article.summary) {
      lines.push(article.summary);
      lines.push('');
    }

    if (article.whyItMatters) {
      lines.push(`> **Why it matters:** ${article.whyItMatters}`);
      lines.push('');
    }

    const pubDate = article.publishedAt
      ? new Date(article.publishedAt).toLocaleDateString()
      : 'Unknown date';

    lines.push(`[Read more](${article.sourceUrl}) | ${article.sourceName || 'Unknown source'} | ${pubDate}`);
    lines.push('');
    lines.push('---');
    lines.push('');

    return lines.join('\n');
  };

  // Build the markdown document
  const sections: string[] = [];

  sections.push('# News Intelligence Digest');
  sections.push('');
  sections.push(`**Prepared for:** ${userName}`);
  sections.push(`**Generated:** ${new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })}`);
  sections.push('');
  sections.push('---');
  sections.push('');

  sections.push('## Summary');
  sections.push('');
  sections.push(`- **Total Articles:** ${articles.length}`);
  sections.push('');
  sections.push('---');
  sections.push('');

  if (articles.length > 0) {
    sections.push('## Articles');
    sections.push('');
    sections.push(...articles.map(formatArticle));
  }

  sections.push('---');
  sections.push('');
  sections.push('*Generated by SSA Intelligence*');

  return sections.join('\n');
}
